# This file is autogenerated by acr-wrap

WRAP_wrap_git_url:=https://github.com/zeux/pugixml.git
WRAP_wrap_git_revision:=v1.15
WRAP_wrap_git_directory:=pugixml
WRAP_wrap_git_patch_directory:=pugixml
WRAP_wrap_git_depth:=1

.PHONY: pugixml_clean pugixml_all

pugixml:
	if [ ! -d "pugixml" -o "v1.15" != "$(shell cd pugixml 2>/dev/null && git rev-parse HEAD)" ]; then rm -rf "pugixml"; ${MAKE} pugixml_all; fi

pugixml_all:
	git clone --no-checkout --depth=1 https://github.com/zeux/pugixml.git pugixml
	cd pugixml && git fetch --depth=1 origin v1.15
	cd pugixml && git checkout FETCH_HEAD
	cp -rf packagefiles/pugixml/* pugixml

pugixml_clean:
	rm -rf pugixml
