stages:
  - test

trigger-ext-u:
  stage: test
  variables:
    JOB_TYPE: $JOB_TYPE
    INITIATOR: $GITLAB_USER_LOGIN
    COMMIT: $CI_COMMIT_SHORT_SHA
    BRANCH: $CI_COMMIT_REF_NAME
  trigger: ghidra/ghidra.ext-u
